blog_home:
    pattern:  /
    defaults: { _controller: cypress_blog.blog_controller:homeAction }

blog_post:
    pattern:  /post/{slug}
    defaults: { _controller: cypress_blog.blog_controller:postAction }

blog_categories:
    pattern:  /categories
    defaults: { _controller: cypress_blog.blog_controller:categoriesAction }

blog_category:
    pattern:  /category/{slug}
    defaults: { _controller: cypress_blog.blog_controller:categoryAction }

blog_tags:
    pattern:  /tags
    defaults: { _controller: cypress_blog.blog_controller:tagsAction }

blog_tag:
    pattern:  /tag/{slug}
    defaults: { _controller: cypress_blog.blog_controller:tagAction }
