blog_home:
    pattern:  /
    defaults:
        _controller: CypressBlogBundle:Blog:home

blog_post:
    pattern:  /post/{slug}
    defaults:
        _controller: CypressBlogBundle:Blog:post

blog_categories:
    pattern:  /categories
    defaults:
        _controller: CypressBlogBundle:Blog:categories

blog_category:
    pattern:  /category/{slug}
    defaults:
        _controller: CypressBlogBundle:Blog:category

blog_tags:
    pattern:  /tags
    defaults:
        _controller: CypressBlogBundle:Blog:tags

blog_tag:
    pattern:  /tag/{slug}
    defaults:
        _controller: CypressBlogBundle:Blog:tag
