blog_home:
    pattern:  /blog
    defaults:
        _controller: BlogBundle:Blog:home

blog_post:
    pattern:  /blog/post/{slug}
    defaults:
        _controller: BlogBundle:Blog:post

blog_categories:
    pattern:  /blog/categories
    defaults:
        _controller: BlogBundle:Blog:categories

blog_category:
    pattern:  /blog/category/{slug}
    defaults:
        _controller: BlogBundle:Blog:category

blog_tags:
    pattern:  /blog/tags
    defaults:
        _controller: BlogBundle:Blog:tags

blog_tag:
    pattern:  /blog/tag/{slug}
    defaults:
        _controller: BlogBundle:Blog:tag
